//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMHalalBackEnd.SmsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://83.66.137.24/PgApiWs", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://83.66.137.24/PgApiWs", ConfigurationName="SmsService.smsserviceSoap")]
    public interface smsserviceSoap {
        
        // CODEGEN: Generating message contract since element name Username from namespace http://83.66.137.24/PgApiWs is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/SmsInsert_1_N", ReplyAction="*")]
        CRMHalalBackEnd.SmsService.SmsInsert_1_NResponse SmsInsert_1_N(CRMHalalBackEnd.SmsService.SmsInsert_1_NRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/SmsInsert_1_N", ReplyAction="*")]
        System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.SmsInsert_1_NResponse> SmsInsert_1_NAsync(CRMHalalBackEnd.SmsService.SmsInsert_1_NRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://83.66.137.24/PgApiWs is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/SmsInsert_N_N", ReplyAction="*")]
        CRMHalalBackEnd.SmsService.SmsInsert_N_NResponse SmsInsert_N_N(CRMHalalBackEnd.SmsService.SmsInsert_N_NRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/SmsInsert_N_N", ReplyAction="*")]
        System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.SmsInsert_N_NResponse> SmsInsert_N_NAsync(CRMHalalBackEnd.SmsService.SmsInsert_N_NRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://83.66.137.24/PgApiWs is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/SmsStatus", ReplyAction="*")]
        CRMHalalBackEnd.SmsService.SmsStatusResponse SmsStatus(CRMHalalBackEnd.SmsService.SmsStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/SmsStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.SmsStatusResponse> SmsStatusAsync(CRMHalalBackEnd.SmsService.SmsStatusRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://83.66.137.24/PgApiWs is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/CreditBalance", ReplyAction="*")]
        CRMHalalBackEnd.SmsService.CreditBalanceResponse CreditBalance(CRMHalalBackEnd.SmsService.CreditBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/CreditBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.CreditBalanceResponse> CreditBalanceAsync(CRMHalalBackEnd.SmsService.CreditBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://83.66.137.24/PgApiWs is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/IdCheck", ReplyAction="*")]
        CRMHalalBackEnd.SmsService.IdCheckResponse IdCheck(CRMHalalBackEnd.SmsService.IdCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/IdCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.IdCheckResponse> IdCheckAsync(CRMHalalBackEnd.SmsService.IdCheckRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://83.66.137.24/PgApiWs is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/IdCheck2", ReplyAction="*")]
        CRMHalalBackEnd.SmsService.IdCheck2Response IdCheck2(CRMHalalBackEnd.SmsService.IdCheck2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/IdCheck2", ReplyAction="*")]
        System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.IdCheck2Response> IdCheck2Async(CRMHalalBackEnd.SmsService.IdCheck2Request request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://83.66.137.24/PgApiWs is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/SmsStatus2", ReplyAction="*")]
        CRMHalalBackEnd.SmsService.SmsStatus2Response SmsStatus2(CRMHalalBackEnd.SmsService.SmsStatus2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/SmsStatus2", ReplyAction="*")]
        System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.SmsStatus2Response> SmsStatus2Async(CRMHalalBackEnd.SmsService.SmsStatus2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SmsInsert_1_NRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SmsInsert_1_N", Namespace="http://83.66.137.24/PgApiWs", Order=0)]
        public CRMHalalBackEnd.SmsService.SmsInsert_1_NRequestBody Body;
        
        public SmsInsert_1_NRequest() {
        }
        
        public SmsInsert_1_NRequest(CRMHalalBackEnd.SmsService.SmsInsert_1_NRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://83.66.137.24/PgApiWs")]
    public partial class SmsInsert_1_NRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<System.DateTime> SendDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<System.DateTime> ExpireDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public CRMHalalBackEnd.SmsService.ArrayOfString Recepients;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Message;
        
        public SmsInsert_1_NRequestBody() {
        }
        
        public SmsInsert_1_NRequestBody(string Username, string Password, System.Nullable<System.DateTime> SendDate, System.Nullable<System.DateTime> ExpireDate, CRMHalalBackEnd.SmsService.ArrayOfString Recepients, string Message) {
            this.Username = Username;
            this.Password = Password;
            this.SendDate = SendDate;
            this.ExpireDate = ExpireDate;
            this.Recepients = Recepients;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SmsInsert_1_NResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SmsInsert_1_NResponse", Namespace="http://83.66.137.24/PgApiWs", Order=0)]
        public CRMHalalBackEnd.SmsService.SmsInsert_1_NResponseBody Body;
        
        public SmsInsert_1_NResponse() {
        }
        
        public SmsInsert_1_NResponse(CRMHalalBackEnd.SmsService.SmsInsert_1_NResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://83.66.137.24/PgApiWs")]
    public partial class SmsInsert_1_NResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CRMHalalBackEnd.SmsService.ArrayOfString SmsInsert_1_NResult;
        
        public SmsInsert_1_NResponseBody() {
        }
        
        public SmsInsert_1_NResponseBody(CRMHalalBackEnd.SmsService.ArrayOfString SmsInsert_1_NResult) {
            this.SmsInsert_1_NResult = SmsInsert_1_NResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SmsInsert_N_NRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SmsInsert_N_N", Namespace="http://83.66.137.24/PgApiWs", Order=0)]
        public CRMHalalBackEnd.SmsService.SmsInsert_N_NRequestBody Body;
        
        public SmsInsert_N_NRequest() {
        }
        
        public SmsInsert_N_NRequest(CRMHalalBackEnd.SmsService.SmsInsert_N_NRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://83.66.137.24/PgApiWs")]
    public partial class SmsInsert_N_NRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<System.DateTime> SendDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<System.DateTime> ExpireDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public CRMHalalBackEnd.SmsService.ArrayOfString Recepients;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public CRMHalalBackEnd.SmsService.ArrayOfString Messages;
        
        public SmsInsert_N_NRequestBody() {
        }
        
        public SmsInsert_N_NRequestBody(string Username, string Password, System.Nullable<System.DateTime> SendDate, System.Nullable<System.DateTime> ExpireDate, CRMHalalBackEnd.SmsService.ArrayOfString Recepients, CRMHalalBackEnd.SmsService.ArrayOfString Messages) {
            this.Username = Username;
            this.Password = Password;
            this.SendDate = SendDate;
            this.ExpireDate = ExpireDate;
            this.Recepients = Recepients;
            this.Messages = Messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SmsInsert_N_NResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SmsInsert_N_NResponse", Namespace="http://83.66.137.24/PgApiWs", Order=0)]
        public CRMHalalBackEnd.SmsService.SmsInsert_N_NResponseBody Body;
        
        public SmsInsert_N_NResponse() {
        }
        
        public SmsInsert_N_NResponse(CRMHalalBackEnd.SmsService.SmsInsert_N_NResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://83.66.137.24/PgApiWs")]
    public partial class SmsInsert_N_NResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CRMHalalBackEnd.SmsService.ArrayOfString SmsInsert_N_NResult;
        
        public SmsInsert_N_NResponseBody() {
        }
        
        public SmsInsert_N_NResponseBody(CRMHalalBackEnd.SmsService.ArrayOfString SmsInsert_N_NResult) {
            this.SmsInsert_N_NResult = SmsInsert_N_NResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SmsStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SmsStatus", Namespace="http://83.66.137.24/PgApiWs", Order=0)]
        public CRMHalalBackEnd.SmsService.SmsStatusRequestBody Body;
        
        public SmsStatusRequest() {
        }
        
        public SmsStatusRequest(CRMHalalBackEnd.SmsService.SmsStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://83.66.137.24/PgApiWs")]
    public partial class SmsStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CRMHalalBackEnd.SmsService.ArrayOfString MessageIDs;
        
        public SmsStatusRequestBody() {
        }
        
        public SmsStatusRequestBody(string Username, string Password, CRMHalalBackEnd.SmsService.ArrayOfString MessageIDs) {
            this.Username = Username;
            this.Password = Password;
            this.MessageIDs = MessageIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SmsStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SmsStatusResponse", Namespace="http://83.66.137.24/PgApiWs", Order=0)]
        public CRMHalalBackEnd.SmsService.SmsStatusResponseBody Body;
        
        public SmsStatusResponse() {
        }
        
        public SmsStatusResponse(CRMHalalBackEnd.SmsService.SmsStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://83.66.137.24/PgApiWs")]
    public partial class SmsStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CRMHalalBackEnd.SmsService.ArrayOfString SmsStatusResult;
        
        public SmsStatusResponseBody() {
        }
        
        public SmsStatusResponseBody(CRMHalalBackEnd.SmsService.ArrayOfString SmsStatusResult) {
            this.SmsStatusResult = SmsStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreditBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreditBalance", Namespace="http://83.66.137.24/PgApiWs", Order=0)]
        public CRMHalalBackEnd.SmsService.CreditBalanceRequestBody Body;
        
        public CreditBalanceRequest() {
        }
        
        public CreditBalanceRequest(CRMHalalBackEnd.SmsService.CreditBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://83.66.137.24/PgApiWs")]
    public partial class CreditBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public CreditBalanceRequestBody() {
        }
        
        public CreditBalanceRequestBody(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreditBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreditBalanceResponse", Namespace="http://83.66.137.24/PgApiWs", Order=0)]
        public CRMHalalBackEnd.SmsService.CreditBalanceResponseBody Body;
        
        public CreditBalanceResponse() {
        }
        
        public CreditBalanceResponse(CRMHalalBackEnd.SmsService.CreditBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://83.66.137.24/PgApiWs")]
    public partial class CreditBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CreditBalanceResult;
        
        public CreditBalanceResponseBody() {
        }
        
        public CreditBalanceResponseBody(int CreditBalanceResult) {
            this.CreditBalanceResult = CreditBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IdCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IdCheck", Namespace="http://83.66.137.24/PgApiWs", Order=0)]
        public CRMHalalBackEnd.SmsService.IdCheckRequestBody Body;
        
        public IdCheckRequest() {
        }
        
        public IdCheckRequest(CRMHalalBackEnd.SmsService.IdCheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://83.66.137.24/PgApiWs")]
    public partial class IdCheckRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public IdCheckRequestBody() {
        }
        
        public IdCheckRequestBody(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IdCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IdCheckResponse", Namespace="http://83.66.137.24/PgApiWs", Order=0)]
        public CRMHalalBackEnd.SmsService.IdCheckResponseBody Body;
        
        public IdCheckResponse() {
        }
        
        public IdCheckResponse(CRMHalalBackEnd.SmsService.IdCheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://83.66.137.24/PgApiWs")]
    public partial class IdCheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IdCheckResult;
        
        public IdCheckResponseBody() {
        }
        
        public IdCheckResponseBody(string IdCheckResult) {
            this.IdCheckResult = IdCheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IdCheck2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IdCheck2", Namespace="http://83.66.137.24/PgApiWs", Order=0)]
        public CRMHalalBackEnd.SmsService.IdCheck2RequestBody Body;
        
        public IdCheck2Request() {
        }
        
        public IdCheck2Request(CRMHalalBackEnd.SmsService.IdCheck2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://83.66.137.24/PgApiWs")]
    public partial class IdCheck2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public IdCheck2RequestBody() {
        }
        
        public IdCheck2RequestBody(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IdCheck2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IdCheck2Response", Namespace="http://83.66.137.24/PgApiWs", Order=0)]
        public CRMHalalBackEnd.SmsService.IdCheck2ResponseBody Body;
        
        public IdCheck2Response() {
        }
        
        public IdCheck2Response(CRMHalalBackEnd.SmsService.IdCheck2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://83.66.137.24/PgApiWs")]
    public partial class IdCheck2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IdCheck2Result;
        
        public IdCheck2ResponseBody() {
        }
        
        public IdCheck2ResponseBody(string IdCheck2Result) {
            this.IdCheck2Result = IdCheck2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SmsStatus2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SmsStatus2", Namespace="http://83.66.137.24/PgApiWs", Order=0)]
        public CRMHalalBackEnd.SmsService.SmsStatus2RequestBody Body;
        
        public SmsStatus2Request() {
        }
        
        public SmsStatus2Request(CRMHalalBackEnd.SmsService.SmsStatus2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://83.66.137.24/PgApiWs")]
    public partial class SmsStatus2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CRMHalalBackEnd.SmsService.ArrayOfString MessageIDs;
        
        public SmsStatus2RequestBody() {
        }
        
        public SmsStatus2RequestBody(string Username, string Password, CRMHalalBackEnd.SmsService.ArrayOfString MessageIDs) {
            this.Username = Username;
            this.Password = Password;
            this.MessageIDs = MessageIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SmsStatus2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SmsStatus2Response", Namespace="http://83.66.137.24/PgApiWs", Order=0)]
        public CRMHalalBackEnd.SmsService.SmsStatus2ResponseBody Body;
        
        public SmsStatus2Response() {
        }
        
        public SmsStatus2Response(CRMHalalBackEnd.SmsService.SmsStatus2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://83.66.137.24/PgApiWs")]
    public partial class SmsStatus2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CRMHalalBackEnd.SmsService.ArrayOfString SmsStatus2Result;
        
        public SmsStatus2ResponseBody() {
        }
        
        public SmsStatus2ResponseBody(CRMHalalBackEnd.SmsService.ArrayOfString SmsStatus2Result) {
            this.SmsStatus2Result = SmsStatus2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface smsserviceSoapChannel : CRMHalalBackEnd.SmsService.smsserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class smsserviceSoapClient : System.ServiceModel.ClientBase<CRMHalalBackEnd.SmsService.smsserviceSoap>, CRMHalalBackEnd.SmsService.smsserviceSoap {
        
        public smsserviceSoapClient() {
        }
        
        public smsserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public smsserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRMHalalBackEnd.SmsService.SmsInsert_1_NResponse CRMHalalBackEnd.SmsService.smsserviceSoap.SmsInsert_1_N(CRMHalalBackEnd.SmsService.SmsInsert_1_NRequest request) {
            return base.Channel.SmsInsert_1_N(request);
        }
        
        public CRMHalalBackEnd.SmsService.ArrayOfString SmsInsert_1_N(string Username, string Password, System.Nullable<System.DateTime> SendDate, System.Nullable<System.DateTime> ExpireDate, CRMHalalBackEnd.SmsService.ArrayOfString Recepients, string Message) {
            CRMHalalBackEnd.SmsService.SmsInsert_1_NRequest inValue = new CRMHalalBackEnd.SmsService.SmsInsert_1_NRequest();
            inValue.Body = new CRMHalalBackEnd.SmsService.SmsInsert_1_NRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.SendDate = SendDate;
            inValue.Body.ExpireDate = ExpireDate;
            inValue.Body.Recepients = Recepients;
            inValue.Body.Message = Message;
            CRMHalalBackEnd.SmsService.SmsInsert_1_NResponse retVal = ((CRMHalalBackEnd.SmsService.smsserviceSoap)(this)).SmsInsert_1_N(inValue);
            return retVal.Body.SmsInsert_1_NResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.SmsInsert_1_NResponse> CRMHalalBackEnd.SmsService.smsserviceSoap.SmsInsert_1_NAsync(CRMHalalBackEnd.SmsService.SmsInsert_1_NRequest request) {
            return base.Channel.SmsInsert_1_NAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.SmsInsert_1_NResponse> SmsInsert_1_NAsync(string Username, string Password, System.Nullable<System.DateTime> SendDate, System.Nullable<System.DateTime> ExpireDate, CRMHalalBackEnd.SmsService.ArrayOfString Recepients, string Message) {
            CRMHalalBackEnd.SmsService.SmsInsert_1_NRequest inValue = new CRMHalalBackEnd.SmsService.SmsInsert_1_NRequest();
            inValue.Body = new CRMHalalBackEnd.SmsService.SmsInsert_1_NRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.SendDate = SendDate;
            inValue.Body.ExpireDate = ExpireDate;
            inValue.Body.Recepients = Recepients;
            inValue.Body.Message = Message;
            return ((CRMHalalBackEnd.SmsService.smsserviceSoap)(this)).SmsInsert_1_NAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRMHalalBackEnd.SmsService.SmsInsert_N_NResponse CRMHalalBackEnd.SmsService.smsserviceSoap.SmsInsert_N_N(CRMHalalBackEnd.SmsService.SmsInsert_N_NRequest request) {
            return base.Channel.SmsInsert_N_N(request);
        }
        
        public CRMHalalBackEnd.SmsService.ArrayOfString SmsInsert_N_N(string Username, string Password, System.Nullable<System.DateTime> SendDate, System.Nullable<System.DateTime> ExpireDate, CRMHalalBackEnd.SmsService.ArrayOfString Recepients, CRMHalalBackEnd.SmsService.ArrayOfString Messages) {
            CRMHalalBackEnd.SmsService.SmsInsert_N_NRequest inValue = new CRMHalalBackEnd.SmsService.SmsInsert_N_NRequest();
            inValue.Body = new CRMHalalBackEnd.SmsService.SmsInsert_N_NRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.SendDate = SendDate;
            inValue.Body.ExpireDate = ExpireDate;
            inValue.Body.Recepients = Recepients;
            inValue.Body.Messages = Messages;
            CRMHalalBackEnd.SmsService.SmsInsert_N_NResponse retVal = ((CRMHalalBackEnd.SmsService.smsserviceSoap)(this)).SmsInsert_N_N(inValue);
            return retVal.Body.SmsInsert_N_NResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.SmsInsert_N_NResponse> CRMHalalBackEnd.SmsService.smsserviceSoap.SmsInsert_N_NAsync(CRMHalalBackEnd.SmsService.SmsInsert_N_NRequest request) {
            return base.Channel.SmsInsert_N_NAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.SmsInsert_N_NResponse> SmsInsert_N_NAsync(string Username, string Password, System.Nullable<System.DateTime> SendDate, System.Nullable<System.DateTime> ExpireDate, CRMHalalBackEnd.SmsService.ArrayOfString Recepients, CRMHalalBackEnd.SmsService.ArrayOfString Messages) {
            CRMHalalBackEnd.SmsService.SmsInsert_N_NRequest inValue = new CRMHalalBackEnd.SmsService.SmsInsert_N_NRequest();
            inValue.Body = new CRMHalalBackEnd.SmsService.SmsInsert_N_NRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.SendDate = SendDate;
            inValue.Body.ExpireDate = ExpireDate;
            inValue.Body.Recepients = Recepients;
            inValue.Body.Messages = Messages;
            return ((CRMHalalBackEnd.SmsService.smsserviceSoap)(this)).SmsInsert_N_NAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRMHalalBackEnd.SmsService.SmsStatusResponse CRMHalalBackEnd.SmsService.smsserviceSoap.SmsStatus(CRMHalalBackEnd.SmsService.SmsStatusRequest request) {
            return base.Channel.SmsStatus(request);
        }
        
        public CRMHalalBackEnd.SmsService.ArrayOfString SmsStatus(string Username, string Password, CRMHalalBackEnd.SmsService.ArrayOfString MessageIDs) {
            CRMHalalBackEnd.SmsService.SmsStatusRequest inValue = new CRMHalalBackEnd.SmsService.SmsStatusRequest();
            inValue.Body = new CRMHalalBackEnd.SmsService.SmsStatusRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.MessageIDs = MessageIDs;
            CRMHalalBackEnd.SmsService.SmsStatusResponse retVal = ((CRMHalalBackEnd.SmsService.smsserviceSoap)(this)).SmsStatus(inValue);
            return retVal.Body.SmsStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.SmsStatusResponse> CRMHalalBackEnd.SmsService.smsserviceSoap.SmsStatusAsync(CRMHalalBackEnd.SmsService.SmsStatusRequest request) {
            return base.Channel.SmsStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.SmsStatusResponse> SmsStatusAsync(string Username, string Password, CRMHalalBackEnd.SmsService.ArrayOfString MessageIDs) {
            CRMHalalBackEnd.SmsService.SmsStatusRequest inValue = new CRMHalalBackEnd.SmsService.SmsStatusRequest();
            inValue.Body = new CRMHalalBackEnd.SmsService.SmsStatusRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.MessageIDs = MessageIDs;
            return ((CRMHalalBackEnd.SmsService.smsserviceSoap)(this)).SmsStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRMHalalBackEnd.SmsService.CreditBalanceResponse CRMHalalBackEnd.SmsService.smsserviceSoap.CreditBalance(CRMHalalBackEnd.SmsService.CreditBalanceRequest request) {
            return base.Channel.CreditBalance(request);
        }
        
        public int CreditBalance(string Username, string Password) {
            CRMHalalBackEnd.SmsService.CreditBalanceRequest inValue = new CRMHalalBackEnd.SmsService.CreditBalanceRequest();
            inValue.Body = new CRMHalalBackEnd.SmsService.CreditBalanceRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            CRMHalalBackEnd.SmsService.CreditBalanceResponse retVal = ((CRMHalalBackEnd.SmsService.smsserviceSoap)(this)).CreditBalance(inValue);
            return retVal.Body.CreditBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.CreditBalanceResponse> CRMHalalBackEnd.SmsService.smsserviceSoap.CreditBalanceAsync(CRMHalalBackEnd.SmsService.CreditBalanceRequest request) {
            return base.Channel.CreditBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.CreditBalanceResponse> CreditBalanceAsync(string Username, string Password) {
            CRMHalalBackEnd.SmsService.CreditBalanceRequest inValue = new CRMHalalBackEnd.SmsService.CreditBalanceRequest();
            inValue.Body = new CRMHalalBackEnd.SmsService.CreditBalanceRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            return ((CRMHalalBackEnd.SmsService.smsserviceSoap)(this)).CreditBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRMHalalBackEnd.SmsService.IdCheckResponse CRMHalalBackEnd.SmsService.smsserviceSoap.IdCheck(CRMHalalBackEnd.SmsService.IdCheckRequest request) {
            return base.Channel.IdCheck(request);
        }
        
        public string IdCheck(string Username, string Password) {
            CRMHalalBackEnd.SmsService.IdCheckRequest inValue = new CRMHalalBackEnd.SmsService.IdCheckRequest();
            inValue.Body = new CRMHalalBackEnd.SmsService.IdCheckRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            CRMHalalBackEnd.SmsService.IdCheckResponse retVal = ((CRMHalalBackEnd.SmsService.smsserviceSoap)(this)).IdCheck(inValue);
            return retVal.Body.IdCheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.IdCheckResponse> CRMHalalBackEnd.SmsService.smsserviceSoap.IdCheckAsync(CRMHalalBackEnd.SmsService.IdCheckRequest request) {
            return base.Channel.IdCheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.IdCheckResponse> IdCheckAsync(string Username, string Password) {
            CRMHalalBackEnd.SmsService.IdCheckRequest inValue = new CRMHalalBackEnd.SmsService.IdCheckRequest();
            inValue.Body = new CRMHalalBackEnd.SmsService.IdCheckRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            return ((CRMHalalBackEnd.SmsService.smsserviceSoap)(this)).IdCheckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRMHalalBackEnd.SmsService.IdCheck2Response CRMHalalBackEnd.SmsService.smsserviceSoap.IdCheck2(CRMHalalBackEnd.SmsService.IdCheck2Request request) {
            return base.Channel.IdCheck2(request);
        }
        
        public string IdCheck2(string Username, string Password) {
            CRMHalalBackEnd.SmsService.IdCheck2Request inValue = new CRMHalalBackEnd.SmsService.IdCheck2Request();
            inValue.Body = new CRMHalalBackEnd.SmsService.IdCheck2RequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            CRMHalalBackEnd.SmsService.IdCheck2Response retVal = ((CRMHalalBackEnd.SmsService.smsserviceSoap)(this)).IdCheck2(inValue);
            return retVal.Body.IdCheck2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.IdCheck2Response> CRMHalalBackEnd.SmsService.smsserviceSoap.IdCheck2Async(CRMHalalBackEnd.SmsService.IdCheck2Request request) {
            return base.Channel.IdCheck2Async(request);
        }
        
        public System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.IdCheck2Response> IdCheck2Async(string Username, string Password) {
            CRMHalalBackEnd.SmsService.IdCheck2Request inValue = new CRMHalalBackEnd.SmsService.IdCheck2Request();
            inValue.Body = new CRMHalalBackEnd.SmsService.IdCheck2RequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            return ((CRMHalalBackEnd.SmsService.smsserviceSoap)(this)).IdCheck2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRMHalalBackEnd.SmsService.SmsStatus2Response CRMHalalBackEnd.SmsService.smsserviceSoap.SmsStatus2(CRMHalalBackEnd.SmsService.SmsStatus2Request request) {
            return base.Channel.SmsStatus2(request);
        }
        
        public CRMHalalBackEnd.SmsService.ArrayOfString SmsStatus2(string Username, string Password, CRMHalalBackEnd.SmsService.ArrayOfString MessageIDs) {
            CRMHalalBackEnd.SmsService.SmsStatus2Request inValue = new CRMHalalBackEnd.SmsService.SmsStatus2Request();
            inValue.Body = new CRMHalalBackEnd.SmsService.SmsStatus2RequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.MessageIDs = MessageIDs;
            CRMHalalBackEnd.SmsService.SmsStatus2Response retVal = ((CRMHalalBackEnd.SmsService.smsserviceSoap)(this)).SmsStatus2(inValue);
            return retVal.Body.SmsStatus2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.SmsStatus2Response> CRMHalalBackEnd.SmsService.smsserviceSoap.SmsStatus2Async(CRMHalalBackEnd.SmsService.SmsStatus2Request request) {
            return base.Channel.SmsStatus2Async(request);
        }
        
        public System.Threading.Tasks.Task<CRMHalalBackEnd.SmsService.SmsStatus2Response> SmsStatus2Async(string Username, string Password, CRMHalalBackEnd.SmsService.ArrayOfString MessageIDs) {
            CRMHalalBackEnd.SmsService.SmsStatus2Request inValue = new CRMHalalBackEnd.SmsService.SmsStatus2Request();
            inValue.Body = new CRMHalalBackEnd.SmsService.SmsStatus2RequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.MessageIDs = MessageIDs;
            return ((CRMHalalBackEnd.SmsService.smsserviceSoap)(this)).SmsStatus2Async(inValue);
        }
    }
}
